const bookData = [
  {
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki and Sharon L. Lechter",
    isbn: "0-446-67745-0",
    genre: ["Personal finance"],
    publishedOn: "April 1, 2000",
    quantity: 50,
    selfNo: "B10",
    pages: 336,
  },
  {
    title: "The Total Money Makeover",
    author: "Dave Ramsey",
    isbn: "0-7852-8877-6",
    genre: ["Personal finance"],
    publishedOn: "September 17, 2003",
    quantity: 30,
    selfNo: "C15",
    pages: 223,
  },
  {
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    isbn: "0-06-055566-1",
    genre: ["Investing"],
    publishedOn: "February 1, 1949",
    quantity: 20,
    selfNo: "A5",
    pages: 623,
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: ["Classic", "Drama"],
    isbn: "1234567890",
    publishedOn: "July 11, 1960",
    quantity: 25,
    selfNo: "A1",
    pages: 281,
  },
  {
    title: "1984",
    author: "George Orwell",
    genre: ["Dystopian", "Science Fiction"],
    isbn: "9876543210",
    publishedOn: "June 8, 1949",
    quantity: 30,
    selfNo: "B2",
    pages: 328,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: ["Classic", "Romance"],
    isbn: "4567890123",
    publishedOn: "April 10, 1925",
    quantity: 20,
    selfNo: "C3",
    pages: 180,
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: ["Fantasy", "Adventure"],
    isbn: "0123456789",
    publishedOn: "July 29, 1954",
    quantity: 35,
    selfNo: "D4",
    pages: 1178,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: ["Classic", "Romance"],
    isbn: "3456789012",
    publishedOn: "January 28, 1813",
    quantity: 15,
    selfNo: "E5",
    pages: 279,
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    genre: ["Science Fiction", "Humor"],
    isbn: "6789012345",
    publishedOn: "October 12, 1979",
    quantity: 40,
    selfNo: "F6",
    pages: 224,
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: ["Coming-of-Age", "Literary Fiction"],
    isbn: "8901234567",
    publishedOn: "July 16, 1951",
    quantity: 22,
    selfNo: "G7",
    pages: 224,
  },
  {
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    genre: ["Magical Realism", "Literary Fiction"],
    isbn: "0123456789",
    publishedOn: "May 30, 1967",
    quantity: 18,
    selfNo: "H8",
    pages: 417,
  },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: ["Dystopian", "Young Adult"],
    isbn: "2345678901",
    publishedOn: "September 14, 2008",
    quantity: 28,
    selfNo: "I9",
    pages: 374,
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    genre: ["Mystery", "Thriller"],
    isbn: "3456789012",
    publishedOn: "March 18, 2003",
    quantity: 23,
    selfNo: "J10",
    pages: 454,
  },
];

export default bookData;
